title: Analysis of Federal Executive .gov domains

collections:
  domains:
    output: true

exclude:
  - script
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - src
  - package.json
  - tsconfig.json
  - package-lock.json
  - webpack.config.js

defaults:
  - scope:
      path: ""
      type: domains
    values:
      layout: domain

plugins:
  - jekyll-seo-tag

true: true
