title: Analysis of federal .gov domains
description: Analysis of what technologies power federal .gov websites - 2021 edition.

collections:
  domains:
    output: true
    permalink: /:collection/:name/

exclude:
  - script
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - src
  - package.json
  - tsconfig.json
  - package-lock.json
  - webpack.config.js

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: domains
    values:
      layout: domain
      date: "2020-01-01"

plugins:
  - jekyll-seo-tag

url: https://ben.balter.com
baseurl: /2021-analysis-of-federal-dotgov-domains
repository: /benbalter/2021-analysis-of-federal-dotgov-domains
